### ISSUE TITLE
"JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchFieldError: no "J" field "mNativeBitmap" in class "Landroid/graphics/Bitmap;" or its superclasses" while using BitmapHelper

### ISSUE THREAD

**Issue by CharlesAMiller** [badpx/IndexBitmap#2]
Hey, I've been poking around with the library, and I'm primarily interested in retrieving a bitmap's color table.

Unfortunately, the TestActivity.java class in the sample package doesn't feature any usage examples of the BitmapHelper's "getColorTable" method.

While trying to use the method in my code:

```
int[] colorTable = new int[16];
Bitmap curBitmap = BitmapFactory.decodeFile(p.getPath());

        if(curBitmap != null)
        {
            BitmapHelper.getColorTable(curBitmap, colorTable);
        }
```

I receive the following error:

> **JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchFieldError: no "J" field "mNativeBitmap" in class "Landroid/graphics/Bitmap;" or its superclasses**

When using code copied from TestActivity.java, "changeColorTable" caused the same error. 

The rest of the log: 

> D/SkBitmapHelper: [skbitmap_helper.cpp:151:getApiLevel]:SDK_INT = 23
> D/SkBitmapHelper: [skbitmap_helper.cpp:37:setupLibrary]:NativeBitmapHelper initialize started
> **A/art: art/runtime/java_vm_ext.cc:410] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchFieldError: no "J" field "mNativeBitmap" in class "Landroid/graphics/Bitmap;" or its superclasses
> A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
> A/art: art/runtime/java_vm_ext.cc:410]   at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:435)
> A/art: art/runtime/java_vm_ext.cc:410]   at void java.lang.Runtime.loadLibrary(java.lang.String, java.lang.ClassLoader) (Runtime.java:370)
> A/art: art/runtime/java_vm_ext.cc:410]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1076)
> A/art: art/runtime/java_vm_ext.cc:410]   at void com.badpx.indexbitmap.BitmapHelper.<clinit>() (BitmapHelper.java:12)**
> 

I've only poked around in the skbitmap_helper.ccp file a little, but seeing as the log output would indicate it gets as far as :
`LOGD("NativeBitmapHelper initialize started");` ,
 I'm guessing this line is the beginning of the crash:
`gBitmap_nativeBitmapFieldID = env->GetFieldID(bitmap_class, "mNativeBitmap", "J");`

Like the log says, I'm running on version 23 of the API. 
Some gradle info:

> compileSdkVersion 25
>             buildToolsVersion "25.0.2"
>             defaultConfig
>                     {
>                         minSdkVersion 18
>                         targetSdkVersion 25
>                     }

And like the README says, I'm using `compile 'com.badpx.indexbitmap:library:1.0.1'`
for my gradle dependency

**Comment by badpx** [comment]
Thanks for your report, please modify build.gradle to use the new version of indexbitmap:
`'com.badpx.indexbitmap:library:1.0.2'`

**Comment by Nishit79** [comment]
Same problem in integrating aviary module. Any solutions to this??
Crash on below line:

NativeFilterProxy.init(FeatherActivity.this);

**Comment by badpx** [comment]
Hi @Nishit79 , `NativeFilterProxy.init(FeatherActivity.this);` is not part of this repo,
please provide more details, including more complete call stack, targetSdkVersion, Android API level and so on, thank you!
